config/routes.rb
Rails.application.routes.draw do
  get '/signup', to:'users#new'
  get '/help', to:'static_pages#help'
  get '/about', to:'static_pages#about'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "static_pages#home"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def hello
    render html: "hello world"
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  #Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "Porfolio"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
    <small>
        The <a href="https://www.railstutorial.org/">Ruby on Rails Tutorial</a>
        by <a href="https://www.michaelhartl.com/">Michael Hartl</a>
    </small>
    <nav>
        <ul>
            <li><%=link_to "About", about_path%></li>
            <li><%=link_to "Help", help_path%></li>
            <li><a href="https://news.railstutorial.org/">News</a></li>
        </ul>
    </nav>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
    <div class="container">
        <%= link_to "Porfolio", root_path, id:"logo"%>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Home", root_path%></li>
            <li><%= link_to "Help", help_path%></li>
            <li><%= link_to "About", about_path%></li>
            <li><%= link_to "Login", '#'%></li>
          </ul>
        </nav>
    </div>
</header>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= csp_meta_tag %>
<%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
<%= javascript_importmap_tags %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
    </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title))%></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    
    <%= render "layouts/rails_default"%>
    <%= render "layouts/shim"%>
  </head>
  <body>
    <%= render "layouts/header"%>
    <div class="container">
      <%= yield %>
      <%= render "layouts/footer"%>
    </div> 
  </body>
</html>

app/views/static_pages/about.html.erb
<% content_for:title, "About" %>
<h1>About this site</h1>
<p>A Ruby on Rails application created during internship at ZigexN VENTURA</p>

app/views/static_pages/help.html.erb
<% content_for:title, "Help" %>
<h1>Rescue your self</h1>
<p>Dont find me :(</p>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
    <h1>Welcome to my Porfolio</h1>
    <p>Find me on Facebook <a target="_blank" href="https://www.facebook.com/tian.d03/">Hoang Thien</a> 
    and Instagram <a target="_blank" href="https://www.instagram.com/tian.d03/">tian.d03</a></p>
    <%= link_to "Subscribe now!",signup_path,class:"btn btn-lg btn-primary"%>
</div>
<%= link_to image_tag("kitten.jpg", alt: "My ultimate boss", width: "600"),
"https://www.ﬂickr.com/photos/deborah_s_perspective/14144861329" %>

app/views/users/new.html.erb
<%= content_for:title, 'Sign up'%>
<h1>Sign up</h1>
<p>Sign up section</p>